plugin: aws_ec2

boto_profile: default

# Enter the region to deploy in
regions:
  - us-east-1

filters:
   instance-state-name: running
# Enter the VPC-ID from terraform outputs or aws console
   vpc-id: vpc-07d9ea7b17e711ac3

hostnames:
    - ip-address

keyed_groups:
    - key: tags.Name
      separator: ''
#strict_permissions: False