plugin: aws_ec2

boto_profile: default

# Enter the region to deploy in
regions:
  - us-east-1

#set aws_access_key and secret_key.
aws_access_key: #Access_Key
aws_secret_key: #Secret_key

filters:
   instance-state-name: running
# Enter the VPC-ID from terraform outputs or aws console
   vpc-id: vpc-03c6aa09cf5084669

hostnames:
    - ip-address

keyed_groups:
    - key: tags.Name
      separator: ''
#strict_permissions: False