---
# tasks file for roles/webservers
- name: Install Extra Packages for Enterprise Linux
  yum: name=epel-release  state=present update_cache=yes

- name: Install Python packages
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - python
    - python-pip

- name: Install apache and php
  yum:
    name:
      - httpd
      - php
    state: present
    update_cache: yes

- name: Start the apache and ensure it starts when we reboot
  service: name=httpd state=started enabled=yes

- name: Configure the php file in the webserver
  template:
    src: ../files/index.php
    dest: "{{path_to_app}}"
    mode: 0755
  notify: restart apache

- name: Creating a simple info page using Gathering facts
  template:
    src: ../files/info.html.j2
    dest: "{{path_to_app}}/info.php"
  notify: restart apache
